---
- name: Install Sysbench and Geekbench
  hosts: all
  become: yes

  tasks:
    - name: Update apt cache
      apt:
       update_cache: yes
    - name: Install required packages
      apt:
        name: ['sysbench', 'postgresql', 'postgresql-contrib']
        state: present

- name: Run Benchmarks
  hosts: all
  gather_facts: false
  become: yes

  tasks:

    - name: Run Sysbench CPU tests with 1 thread
      command: sysbench cpu --cpu-max-prime=20000 --threads=1 run
      register: cpu_1_thread_result
      changed_when: false

    - name: Run Sysbench CPU tests with 2 threads
      command: sysbench cpu --cpu-max-prime=20000 --threads=2 run
      register: cpu_2_threads_result
      changed_when: false

    - name: Run Sysbench CPU tests with 4 threads
      command: sysbench cpu --cpu-max-prime=20000 --threads=4 run
      register: cpu_4_threads_result
      changed_when: false  

    - name: Run Sysbench CPU tests with 8 threads
      command: sysbench cpu --cpu-max-prime=20000 --threads=8 run
      register: cpu_8_threads_result
      changed_when: false  


    - name: Run Sysbench memory tests with 1 thread
      command: sysbench memory --memory-block-size=1M --memory-total-size=6G --threads=1 run
      register: memory_1_thread_result
      changed_when: false

    - name: Run Sysbench memory tests with 2 threads
      command: sysbench memory --memory-block-size=1M --memory-total-size=6G --threads=2 run
      register: memory_2_threads_result
      changed_when: false

    - name: Run Sysbench memory tests with 4 threads
      command: sysbench memory --memory-block-size=1M --memory-total-size=6G --threads=4 run
      register: memory_4_threads_result
      changed_when: false     

    - name: Run Sysbench memory tests with 8 threads
      command: sysbench memory --memory-block-size=1M --memory-total-size=6G --threads=8 run
      register: memory_8_threads_result
      changed_when: false             

    # - name: Run Pgbench
    #   command:  time pgbench -c 5 -j 5 --aggregate-interval=5 -P 5 -l -r -T 30 -U postgres bmark
    #   register: pg_result
    #   changed_when: false         

    # - name: Run Sysbench fileio tests with 1 thread
    #   command: sysbench fileio --file-total-size=1G --file-test-mode=rndrw --time=60 --max-requests=0 run
    #   register: fileio_1_thread_result
    #   changed_when: false

    # - name: Run Sysbench fileio tests with 4 threads
    #   command: sysbench fileio --file-total-size=1G --file-test-mode=rndrw --time=60 --max-requests=0 run
    #   register: fileio_4_threads_result
    #   changed_when: false

    # - name: Run Geekbench
    #   command: /path/to/geekbench
    #   register: geekbench_result
    #   changed_when: false


- name: Create log file for benchmark results
  hosts: all
  gather_facts: false
  tasks:
    - name: Create a file
      file:
        path: results/{{ inventory_hostname }}.log
        state: touch
      delegate_to: localhost   
        
    - name: Create log file
      lineinfile:
        line: "{{ item.stdout }}"
        dest: "results/{{ inventory_hostname }}.log"
      delegate_to: localhost    
      loop:
        - "{{ cpu_1_thread_result }}"
        - "{{ cpu_2_threads_result }}"
        - "{{ cpu_4_threads_result }}"
        - "{{ cpu_8_threads_result }}"
        - "{{ memory_1_thread_result }}"
        - "{{ memory_2_threads_result }}"
        - "{{ memory_4_threads_result }}"
        - "{{ memory_8_threads_result }}"
       # - "{{ pg_result }}"
# - name: Save benchmark results to separate logs
#   tasks:
#   - name: saving ... 
#     copy:
#       dest: "{{ inventory_hostname }}.log"
#       content: "{{ item.stdout }}"
#     delegate_to: localhost
#     loop:
#       - "{{ cpu_1_thread_result }}"
#       - "{{ cpu_4_threads_result }}"
#       - "{{ memory_1_thread_result }}"
#       - "{{ memory_4_threads_result }}"
#       # - "{{ fileio_1_thread_result }}"
#       # - "{{ fileio_4_threads_result }}"
#       # - "{{ geekbench_result }}"  
      
